### ISSUE TITLE
script not working

### ISSUE THREAD

**Issue by BigGod12** [shakilkhan1801/Token-Sending-bot-Low-gas-Fee-#1]
Hi, why this error when i used the script, even after i already installed all the dependencies with "npm install" and it ran successfully
"vboxuser@zen-bassi:~/Documents/Token-Sending-bot-Low-gas-Fee-$ node mint.js
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module './wallets'
Require stack:
- /home/vboxuser/Documents/Token-Sending-bot-Low-gas-Fee-/mint.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/home/vboxuser/Documents/Token-Sending-bot-Low-gas-Fee-/mint.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/vboxuser/Documents/Token-Sending-bot-Low-gas-Fee-/mint.js' ]"

and there is no directory to input the receiver addresses to get the mint token, should i create the directory myself??? thank you

**Comment by shakilkhan1801** [comment]
> Hi, why this error when i used the script, even after i already installed all the dependencies with "npm install" and it ran successfully "vboxuser@zen-bassi:~/Documents/Token-Sending-bot-Low-gas-Fee-$ node mint.js internal/modules/cjs/loader.js:892 throw err; ^
> 
> Error: Cannot find module './wallets' Require stack:
> 
> * /home/vboxuser/Documents/Token-Sending-bot-Low-gas-Fee-/mint.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:745:27)
>   at Module.require (internal/modules/cjs/loader.js:961:19)
>   at require (internal/modules/cjs/helpers.js:92:18)
>   at Object. (/home/vboxuser/Documents/Token-Sending-bot-Low-gas-Fee-/mint.js:5:17)
>   at Module._compile (internal/modules/cjs/loader.js:1072:14)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
>   at Module.load (internal/modules/cjs/loader.js:937:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:778:12)
>   at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
>   at internal/main/run_main_module.js:17:47 {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/home/vboxuser/Documents/Token-Sending-bot-Low-gas-Fee-/mint.js' ]"
> 
> and there is no directory to input the receiver addresses to get the mint token, should i create the directory myself??? thank you

check now
